### ISSUE TITLE
Error during deployment of ELMS solution

### ISSUE THREAD

**Issue by Takou-DevAp** [Azure-Samples/iotedge-logging-and-monitoring-solution#25]
Hi everyone, 

I tried to deploy the ELMS solution as described in the readme document:
link: https://github.com/Azure-Samples/iotedge-logging-and-monitoring-solution
 steps to reproduce:
 0- I opened power shell with elevated rights
 1- I logged in with: az login command
2- I ran the deployment script
3- I choose a custom deployment
4- I choose an existing azure subscription, i choose existing resource group, existing IOT hub, existing storage, an existing log analytics work space, etc..
5-etc..

but when the deployment starts, it throws this following error, i shortened the output since its the same thing all over:

Creating resource group deployment.
ERROR: {"status":"Failed","error":{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"message\": \"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"RoleAssignmentUpdateNotPermitted\\\",\\r\\n    \\\"message\\\": \\\"Tenant ID, application ID, principal ID, and scope are not allowed to be updated.\\\"\\r\\n  }\\r\\n}\"\r\n          }\r\n        ]\r\n      }\r\n    ]\r\n  }\r\n}"}]}}
Something went wrong with the resource group deployment. Ending script.
Au caractère C:\Users\Administrateur\Documents\iotedge-logging-and-monitoring-solution\Scripts\deploy.ps1:1012 : 9
+         throw "Something went wrong with the resource group deploymen ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Something went ... Ending script.:String) [], RuntimeException
    + FullyQualifiedErrorId : Something went wrong with the resource group deployment. Ending script.

 this message clearly says: Tenant ID, application ID, principal ID, and scope are not allowed to be updated.

Has anyone have any solution for this ?
Link to the deployment script: https://github.com/Azure-Samples/iotedge-logging-and-monitoring-solution/blob/main/Scripts/deploy.ps1

**Comment by Takou-DevAp** [comment]
And What have you tried so far ?
On my side,
I tried to check if there was any function that treats these IDs and i
found the New-Guid function:

function Get-EnvironmentHash(
    [int]$hash_length = 8
) {
    $env_hash = (New-Guid).Guid.Replace('-', '').Substring(0, $hash_length
).ToLower()

    return $env_hash
}


What the function does is: it creates a Guid and takes the first part and
then uses it in the process.
Now the question was how to retrieve my tenant IDs so that it uses it in
the process.
As the first command 'az login' connects us to azure and gives the Tenant
ID as part of the output, I changed the function so that it gives directly
the needed part of my tenant ID but it didn't work.

Now I don't know what to do next... I don't know if there is anything to do
on azure portal: changed parameters or set parameters.

Le jeu. 7 avr. 2022 à 14:29, rashmisingh622 ***@***.***> a
écrit :

**Comment by Takou-DevAp** [comment]
Ok, I'll check what you first did and see,
Anyways, I also found another issue while trying other times, as you can
see in the picture below.
I think that your second message error gives a hint.
Please,  let me know what you get as result.


Le jeu. 7 avr. 2022 à 15:18, rashmisingh622 ***@***.***> a
écrit :

**Comment by eedorenko** [comment]
@rashmisingh622 try to update this line https://github.com/Azure-Samples/iotedge-logging-and-monitoring-solution/blob/5e688eddb982967ec03e352291e39ffbb5408f80/Templates/eventhubs-deploy.json#L103 like this
```
 "namespaceAuthRulesApiVersion": "2021-11-01"
```

**Comment by eedorenko** [comment]
Looks like they broke API version. Fixed in this PR #26 .

**Comment by marvin-garcia** [comment]
@Takou-DevAp and @rashmisingh622 ,  can you pull the latest changes from main an re-run the wizard? there were some fixes pushed this week.

**Comment by Takou-DevAp** [comment]
> 

Alright Thank you very much for your help!

**Comment by Takou-DevAp** [comment]
Hello everyone once again,
I faced this issue and tried to understand why it happens but couldn't do anything about it can you help me out ? @marvin-garcia, @eedorenko ?

![new Elms deployment error](https://user-images.githubusercontent.com/90444872/163980380-098b500f-af81-4f98-9edb-b8bd46936427.PNG)

**Comment by Takou-DevAp** [comment]
Hi Marvin,

I'm facing this issue now even if the deployment succeeded , I'm not sure
why. Do you have any hints ?

Le jeu. 7 avr. 2022 à 21:30, Marvin Garcia ***@***.***> a
écrit :
