### ISSUE TITLE
Uploading Messages via IoTMessage fails sometimes

### ISSUE THREAD

**Issue by robertokcanale** [Azure-Samples/iotedge-logging-and-monitoring-solution#7]
### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
When deploying the IoTMetricsCollector via IoTHub, you can set the environment variable UploadTarget = IoTMessage .

It worked for 12 hours after deployment then stopped. Worked 10 mins again during the night and then stopped working. Changed deployment to UploadTarget = AzureMetrics (works) and then reverted to UploadTarget = IoTMessage. I did this a few times. Reverting to UploadTarget = IoTMessage works only sometimes, not always

### Any log messages given by the failure
N/A

### OS and Version?
Linux Ubuntu Server 18

### Versions
edgeHub and edgeAgent 1.2.3
IoTEdgeMetricsCollector 1.0

I Have no specific logs that might help. It seems that the device, log analytics and function app work, but it is then not possible to visualize the data on the IoTHub Workbook.

**Comment by MagdaPaj** [comment]
@robertokcanale your failure is probably related to the problem described [in this PR](https://github.com/Azure-Samples/iotedge-logging-and-monitoring-solution/pull/11).

You can either wait for the merge or just update your current Function App Configuration by adding `WEBSITE_LOAD_USER_PROFILE ` with value `1`. If you try it, please let me know if the failure is fixed.

**Comment by robertokcanale** [comment]
@MagdaPaj thank you for your comment and directives. 
I just made the appropriate changes and it worked! IoTMessages started coming in in less than two minutes. 
To me, the failure seems fixed (I'll monitor it in the next 48 hrs and will let you know if something goes wrong). 

Thanks
